### PR TITLE
Added ALT-U bootcamp

### PR DESCRIPTION
**Pull request by nylemusgrave**
I'm director for ALT-U training program and would like to add our bootcamp to the list.

### CODE REVIEW

**Comment by rkuykendall** [comment]
Hey @nylemusgrave, thanks for the contribution! Excited to have your bootcamp added. The different levels are really interesting.

The only thing I see that needs tweaked are cities and topics. We use slugs from these two lists for those:

https://github.com/Thinkful/bootcamp-finder/blob/master/topics.yml
https://github.com/Thinkful/bootcamp-finder/blob/master/cities.yml

So `iOS` would be `ios` and `User Interface Development` would just be `ui` and so on. Same with cities. It doesn't look like we have a `saint-louis` yet though, so feel free to add it! As for adding new topics, we try not to. We're actually trying to cut that topic list down. We generally only want topics we think students would be searching for a whole page of. That means definitely Swift Bootcamps, but not Debugging Bootcamps since that makes less sense, definitely React but not Reflux, Definetly Javascript but not ES6, etc.

You can work on these tweaks yourself and I'll check them out when you update, or sometime this week I can merge your PR and work on them. :)

**Comment by nylemusgrave** [comment]
So for the topics do I use the display name in the YML file or use the slug?

**Comment by nylemusgrave** [comment]
Updated the topics to slugs as well.

**Comment by nylemusgrave** [comment]
@rkuykendall Anything else need to be done for this? Excited about getting on your site!

**Comment by nylemusgrave** [comment]
Any news on this? Just wanting to make sure I’ve done everything I need to.

NYLE MUSGRAVE
 <http://www.nashinnovations.com/>618-420-8447
nyle@fivepackcreative.com

**Comment by jcudmore** [comment]
Hey @nylemusgrave. This looks great! We're merging now. It should be live by EOD. thanks for contributing!

**Comment by rkuykendall** [comment]
Hey @nylemusgrave, you're live! Thanks for the addition, especially as our first Saint Louis bootcamp, and I hope lots of students learn about your bootcamp!

https://www.thinkful.com/bootcamps/alt-u

**Comment by nylemusgrave** [comment]
Thanks so much!

NYLE MUSGRAVE
 <http://www.nashinnovations.com/>618-420-8447
nyle@fivepackcreative.com

**Pull request merged**
