### PR TITLE
Update some logos, reduce file size.

### PR DESCRIPTION
**Pull request by rkuykendall**

### CODE REVIEW

**Comment by bhaumik** [comment]
Looks good but should we really update our logo? I'd rather want the word Thinkful written out in places like:  
screen shot 2016-03-18 at 3 02 51 pm

The "T" doesn't have enough brand recognition yet to stand alone.

**Comment by bhaumik** [comment]
@jcudmore thoughts?

**Comment by rkuykendall** [comment]
I like that it's written out, but I think the size is hurting us, and it goes against what we do for every other logo.

**Comment by jcudmore** [comment]
I agree with @rkuykendall. Let's use the "T". It's the style we are using for others schools as well.

**Comment by bhaumik** [comment]
:+1:

**Pull request merged**
