### PR TITLE
Digital Unicorn

### PR DESCRIPTION
**Pull request by DanielUnicorn**

### CODE REVIEW

**Comment by jcudmore** [comment]
Hey @DanielUnicorn thanks for submitting your school! I see you also added a new topic slug for symfony. Thanks for following the rules so closely. Your listing should appear shortly! Let me know if you have any questions.

**Comment by DanielUnicorn** [comment]
@jcudmore @benjaminEwhite 

Hi guys,

Is there a problem with our pull request that you decided to revert it?

Regards,
Dan

**Comment by jcudmore** [comment]
Hey @DanielUnicorn. Very sorry! We had an issue with the app yesterday and are looking into it. Unfortunately, you may have to resubmit your school data.  I hope to give you an update on this soon. Sorry again for the inconvenience. 

- Justin / Thinkful

**Comment by DanielUnicorn** [comment]
Hi @jcudmore,

Thank you for getting back.

Should i create new pull request?

**Comment by jcudmore** [comment]
Hey @DanielUnicorn - The app is back to normal. Please re-submit your PR. Sorry about that. I promise we'll get it published quickly. 

Thanks!

**Comment by jcudmore** [comment]
Hey @DanielUnicorn. We were able to get your school merged without the need for an additional PR. https://www.thinkful.com/bootcamps/digitalunicorn/

Let me know if you have any questions! Thanks, Justin

**Comment by DanielUnicorn** [comment]
Thanks @jcudmore 

Really appreciate your help

**Pull request merged**
