### PR TITLE
Add Le Wagon

### PR DESCRIPTION
**Pull request by ssaunier**
Hello @tati 👋 ,

Please find this Pull Request to add [Le Wagon](https://www.lewagon.com) to the Thinkful Bootcamp Finder. I'll be happy to answer your questions or provide edits.

Thank you very much!

### CODE REVIEW

**Comment by ssaunier** [comment]
(Sorry I'm not sure how to write the multi-line string to make the Python parser happy...)

**Comment by tati** [comment]
@ssaunier thank you for making PR - will look at shortly and let you know if I have any questions

**Comment by ssaunier** [comment]
Hi @tati, hope everything is all right. Don't hesitate to ping me if you need more info :)
Best 👋

**Comment by ssaunier** [comment]
Hi there 👋 

Don't mean to be rude or pushy, let me know if you need additional information or if I need to update the diff.

Thank you!

**Pull request merged**
