### PR TITLE
add f&c

### PR DESCRIPTION
**Pull request by izaakrogan**
Let me know if you would like the Github/LinkedIn accounts for our alumni re placement or any other info. Thanks 👍

### CODE REVIEW

**Comment by izaakrogan** [comment]
Hello?

**Comment by jcudmore** [comment]
Hey @izaakrogan. Sorry for the delay. We'll get this added right away.

**Comment by rkuykendall** [comment]
Hey @izaakrogan! Sorry for the delays, we're still working on integrating these PRs into our normal engineering cycles.

https://www.thinkful.com/bootcamps/founders-and-coders

There's Founders & Coders! I had to do a little tweaking to get the topics to match the slugs in our `topics.yml file so it would work, but didn't touch any of the other data. It sounds like you have a great program, and I hope we start sending some students your way!

**Comment by izaakrogan** [comment]
@rkuykendall @jcudmore Thank you!! And thanks for taking the time to fix the topics 👍 👍

**Comment by jcudmore** [comment]
Hey @izaakrogan. I’m working on verifying all our data, and I haven’t been able to find any information on your website about your job guarantee. This is something we really believe in, and think it’s very important for students to know as much as possible about the outcomes of a program. Do you have a link to any official information on this? thanks

**Comment by izaakrogan** [comment]
@jcudmore sure. will get something over to you asap

**Comment by izaakrogan** [comment]
On second reading, I realise you have't asked for stats but details of a 'job guarantee'. We can guarentee a job inasmuch as every graduate who has wanted a job has one i.e. 30/30 of them (with one who didn't want a job). A 'job guarentee' sounds like a money back deal and as we don't charge anything that doesn't really apply. If you take it as 'a guaranteed job' I think we qualify. 

Side note: I'm aware that I don't want to go giving out people's data willy nilly. LinkedIn is already public info so I'm comfortable giving out links to profiles. I hope that's ok. One of our grads doesn't have linkedIn, presumably because they don't want to share their data - case in point! Would you be ok with a first name and a job title for them? I can email this to you or otherwise, just let me know what works best.

This conversation has reminded me that we should have this info up on the site anyway. I'll get around to it tonight. If you would prefer to wait for me to get do that I can post the link in a few hours.

I'm happy to Skype over any of this if useful. Thank you for putting time into this!

**Comment by jcudmore** [comment]
Hey @izaakrogan. Your reasoning behind the 'guaranteed job' makes perfect sense. With a free program, that wouldn't really be a thing. This is a really fantastic program, and it's great to hear how well your students are doing.

I also totally get wanting to be careful with user data. We did this not by making student data public, but by having it [verified by a third-party accounting firm](https://www.thinkful.com/bootcamp-jobs-stats/audit-results-feb-2016.pdf). I understand how this might not be money well spent for a student-donation-funded venture though. So we might not be able to say 'outcomes verified', but at the same time I really need to think about how we can tackle that with smaller, more student-owned bootcamps like yours that are doing so much good.

Thanks again for being so forthcoming and I really hope we're sending some great students your way! Our analytics show we've already had 35 students check out your profile on the site, and that's climbing.

**Pull request merged**
