### PR TITLE
coding campus to v school

### PR DESCRIPTION
**Pull request by Sburdge**

### CODE REVIEW

**Comment by rkuykendall** [comment]
Hey @Sburdge! I love the new branding. Are you still working on this PR? Here's a few notes:

- The topics look pretty good, but I noticed one or two aren't in the 'slug' form from [topics.yml](https://github.com/Thinkful/bootcamp-finder/blob/master/topics.yml). If you want I can just fix those when I merge it.
- The logo looks great, but if you want to auto-crop out the whitespace it will show up larger on the page.

**Comment by Sburdge** [comment]
Excellent, will do right now Robert.

Sariah

On Tue, May 17, 2016 at 11:43 AM, Robert Kuykendall <
notifications@github.com> wrote:

> Hey @Sburdge <https://github.com/Sburdge>! I love the new branding. Are
> you still working on this PR? Here's a few notes:
>
>    - The topics look pretty good, but I noticed one or two aren't in the
>    'slug' form from topics.yml
>    <https://github.com/Thinkful/bootcamp-finder/blob/master/topics.yml>.
>    If you want I can just fix those when I merge it.
>    - The logo looks great, but if you want to auto-crop out the
>    whitespace it will show up larger on the page.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Thinkful/bootcamp-finder/pull/23#issuecomment-219796558>
>



-- 
*Sariah Masterson*
V School | Program Director

mail | smasterson@vschool.io
mobile  | *801.822.2561*

web | vschool.io
twitter | twitter.com/vschoolhq
ig | i
<http://t.sidekickopen52.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQsBjPW2zGJSR643YvgN76g6j91DNXxf2-4pXq03?t=http%3A%2F%2Finstagram.com%2Fvschool_&si=5804922305249280&pi=40a76b3b-e909-488a-fcd5-e3bdfd08d17c>
nstagram.com/vschool_ <http://instagram.com/vschool_>
facebook | facebook.com/vschoolhq



V School USA
379 N University Ave
Provo UT, 84601

**Comment by Sburdge** [comment]
One quick question - we also have a part time evening JS course and an iOS
course for current developers, but I know you prefer not to list
non-immersive bootcamp courses. Would these courses be considered under
that umbrella? You can read more about them here:

http://vschool.io/en/courses/4/

http://vschool.io/en/courses/3/



On Tue, May 17, 2016 at 12:15 PM, Sariah Masterson <smasterson@vschool.io>
wrote:

> Excellent, will do right now Robert.
>
> Sariah
>
> On Tue, May 17, 2016 at 11:43 AM, Robert Kuykendall <
> notifications@github.com> wrote:
>
>> Hey @Sburdge
>> <http://t.sidekickopen52.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQsBjPW2zGJSR643YvgN76g6j91DNXxf2-4pXq03?t=https%3A%2F%2Fgithub.com%2FSburdge&si=5804922305249280&pi=1b8a9b8c-fa3f-492e-ad0f-626451ae0190>!
>> I love the new branding. Are you still working on this PR? Here's a few
>> notes:
>>
>>    - The topics look pretty good, but I noticed one or two aren't in the
>>    'slug' form from topics.yml
>>    <https://github.com/Thinkful/bootcamp-finder/blob/master/topics.yml>.
>>    If you want I can just fix those when I merge it.
>>    - The logo looks great, but if you want to auto-crop out the
>>    whitespace it will show up larger on the page.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <http://t.sidekickopen52.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQsBjPW2zGJSR643YvgN76g6j91DNXxf2-4pXq03?t=https%3A%2F%2Fgithub.com%2FThinkful%2Fbootcamp-finder%2Fpull%2F23%23issuecomment-219796558&si=5804922305249280&pi=1b8a9b8c-fa3f-492e-ad0f-626451ae0190>
>>
>
>
>
> --
> *Sariah Masterson*
> V School | Program Director
>
> mail | smasterson@vschool.io
> mobile  | *801.822.2561 <801.822.2561>*
>
> web | vschool.io
> twitter | twitter.com/vschoolhq
> ig | i
> <http://t.sidekickopen52.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQsBjPW2zGJSR643YvgN76g6j91DNXxf2-4pXq03?t=http%3A%2F%2Finstagram.com%2Fvschool_&si=5804922305249280&pi=40a76b3b-e909-488a-fcd5-e3bdfd08d17c>
> nstagram.com/vschool_ <http://instagram.com/vschool_>
> facebook | facebook.com/vschoolhq
>
>
>
> V School USA
> 379 N University Ave
> Provo UT, 84601
>



-- 
*Sariah Masterson*
V School | Program Director

mail | smasterson@vschool.io
mobile  | *801.822.2561*

web | vschool.io
twitter | twitter.com/vschoolhq
ig | i
<http://t.sidekickopen52.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQsBjPW2zGJSR643YvgN76g6j91DNXxf2-4pXq03?t=http%3A%2F%2Finstagram.com%2Fvschool_&si=5804922305249280&pi=1b8a9b8c-fa3f-492e-ad0f-626451ae0190>
nstagram.com/vschool_ <http://instagram.com/vschool_>
facebook | facebook.com/vschoolhq



V School USA
379 N University Ave
Provo UT, 84601

**Comment by Sburdge** [comment]
@rkuykendall k I think it should be good to go. Let me know if you need any additional changes and if I can add those two other classes. Thanks!

**Comment by rkuykendall** [comment]
@Sburdge Yeah those courses don't sound like what the site is for. It's focused on bigger, noob-to-job bootcamps. Thanks for the PR and I'll get this merged in ASAP! Will post a link here when it's live.

**Comment by Sburdge** [comment]
Sounds great, thanks Robert!

On Fri, May 20, 2016 at 9:19 AM, Robert Kuykendall <notifications@github.com
> wrote:

> @Sburdge <https://github.com/Sburdge> Yeah those courses don't sound like
> what the site is for. It's focused on bigger, noob-to-job bootcamps. Thanks
> for the PR and I'll get this merged in ASAP! Will post a link here when
> it's live.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Thinkful/bootcamp-finder/pull/23#issuecomment-220635048>
>



-- 
*Sariah Masterson*
V School | Program Director

mail | smasterson@vschool.io
mobile  | *801.822.2561*

web | vschool.io
twitter | twitter.com/vschoolhq
ig | i
<http://t.sidekickopen52.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQsBjPW2zGJSR643YvgN76g6j91DNXxf2-4pXq03?t=http%3A%2F%2Finstagram.com%2Fvschool_&si=5804922305249280&pi=1330bdf6-36c8-4faf-9fd0-34696491bdcb>
nstagram.com/vschool_ <http://instagram.com/vschool_>
facebook | facebook.com/vschoolhq



V School USA
379 N University Ave
Provo UT, 84601

**Comment by rkuykendall** [comment]
@Sburdge so sorry this got lost in the product shuffle. They're live now! https://www.thinkful.com/bootcamps/v-school

**Comment by Sburdge** [comment]
Thank you!

On Tue, Jun 7, 2016 at 2:13 PM, Robert Kuykendall <notifications@github.com>
wrote:

> @Sburdge <https://github.com/Sburdge> so sorry this got lost in the
> product shuffle. They're live now!
> https://www.thinkful.com/bootcamps/v-school
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Thinkful/bootcamp-finder/pull/23#issuecomment-224399743>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEdN1Xh9NLkz4-cuYA_I2QUeu26G22_2ks5qJdDpgaJpZM4IeX39>
> .
>



-- 
*Sariah Masterson*
V School | Program Director

mail | smasterson@vschool.io
mobile  | *801.822.2561*

web | vschool.io
twitter | twitter.com/vschoolhq
ig | i <http://instagram.com/vschool_>nstagram.com/vschool_
<http://instagram.com/vschool_>
facebook | facebook.com/vschoolhq



V School USA
379 N University Ave
Provo UT, 84601

**Pull request merged**
