### PR TITLE
adding in Sabio information and files

### PR DESCRIPTION
**Pull request by fierro**
This is the information for Sabio. I am one of the founders of Sabio.

### CODE REVIEW

**Comment by rkuykendall** [comment]
Hey @fierro! Thanks for the addition, it looks like a really awesome bootcamp. Your topic slugs look good from what I can tell, but would you mind changing `los angeles` to the `los-angeles` slug from [cities.yml](https://github.com/Thinkful/bootcamp-finder/blob/master/cities.yml)? Also I don't think newport beach is far enough from LA to work as it's own city page. Maybe if we had more than 3 LA bootcamps, but right now that grouping isn't really big enough to break down.

Thanks a lot!

**Comment by fierro** [comment]
I changed LA and removed NB. What are the guidelines around different cities? I know NB looks close to us but the reason we opened down there is that people, for the most part, would not travel that far to attend a bootcamp. It is in a different county of CA as well. Said another way, if you want to go to a bootcamp and want to drive the distance between those two cities would disqualify 1 over the other.

Just looking for guidance here. 

If you need some testimonials I can provide.

**Comment by rkuykendall** [comment]
@fierro That's a really fair argument. Also, they're two physical locations, so it really doesn't make sense not to include them both. I think my brain was in a topics-mindset, where consolidation is important. I'm merging things and putting them live now, so I'll just add NB back for you. Sorry for the trouble!

**Comment by rkuykendall** [comment]
Sabio is online! https://www.thinkful.com/bootcamps/sabio

**Comment by fierro** [comment]
Thank you very much!!!!

Date: Tue, 7 Jun 2016 13:14:09 -0700

**Pull request merged**
